### ISSUE TITLE
Variance-covariance matrix from `svyglm` as model output?

### ISSUE THREAD

**Issue by ckonichipaulo** [ssdavenport/microsynth#25]
Hi,

First off, thanks so much for the package! I'm reaching out to see if it would be possible to add the variance-covariance matrix from the `svyglm` regression as part of the model output (maybe together with the other outputs in `svyglm.stats`?).
The reason for that is that I would like to report more than one confidence interval (from permutations) without having to re-run the model again. From my understanding, the variance-covariance is used to compute `delta.out` and that's the only missing piece that I can't recover to build a confidence interval with a different alpha on top of the one used in the model.

Again, many thanks!

**Comment by ssdavenport** [comment]
Cinthia,

Thank you!

Unfortunately I don't have a lot of bandwidth to maintain the package right now, but if you wanted to push a request to the github page, I would be happy to review it and consider it for acceptance!

Steve

Sent via Superhuman ( ***@***.*** )

**Comment by ckonichipaulo** [comment]
Hi Steven!

Thank you for your reply! I created a [PR](https://github.com/ssdavenport/microsynth/pull/26) but this is my first time ever contributing to a package, so please let me know if there is anything else that I should add to it.

Thanks,
Cinthia

**Comment by ssdavenport** [comment]
Awesome! thank you for your contribution Cinthia

Sent via Superhuman ( ***@***.*** )
